export * from 'whatwg-url';
import { isValidURLObject } from './lib/valid/URL';
export { isValidURLObject };
export declare const isValidURL: typeof isValidURLObject;
export * from './lib/URLImpl';
import { URLImpl } from './lib/URLImpl';
import { URLSearchParams } from './lib/URLSearchParams';
import { URL } from './lib/URL';
export { URL, URLImpl, URLSearchParams };
export default URL;
